print('================================ Desafio 4 - Aula 06 ==================================')
t1 = input('Digite algo:')
print('O tipo primitivo de {} é da classe {}'.format(t1,type(t1)))
print('{} É alfanumerico? {}'.format(t1,t1.isalnum()))            #, t1.isalnum())
print('{} É um digito? {} '.format(t1,t1.isnumeric()))            #, t1.isnumeric())
print('{} Tem na tabela ascii? {} '.format(t1,t1.isascii()))      #, t1.isascii())
print('{} É um digito? {}'.format(t1,t1.isdigit()))               #, t1.isdigit())
print('{} Tem apenas espaço? {}'.format(t1,t1.isspace()))             #, t1.isspace())
print('{} Tem apenas letras minusculas? {}'.format(t1,t1.islower()))  #, t1.islower())
print('{} Tem apenas letras maiusculas? {}'.format(t1,t1.isupper()))  #, t1.isupper())
print('{} Esta capitalizada? {}'.format(t1,t1.istitle()))         #, t1.istitle())